version: 1
serverName: "myserverName"
messages:
  email:
    subject: "User {username} has joined your server {servername}"
    content: "A user with name {username} has joined your server on {datetime} at coordinates {coords}"
time:
  datetime-format: "yyyy-MM-dd HH:mm:ss"
  zone: "Europe/Berlin"
notification:
  email:
    recipients: # add your recipients
      - "recipient@email.com"
      - "recipient2@email.com"
    from: "fromme@email.com" # edit the sender
    enabled: "true"
    loadFromEnv:
      enabled: "true"
      key: "SMTP_PASSWORD" # load password for authentication from env var by default, if false use field below. Recommended usage!
    serverAddress: "smtp.myserver.com"
    port: 465
    username: "myusername"
    password: "mypassword"
# room for other systems configuration