version: 1
serverName: "myserverName"
messages:
  email:
    subject: "User {username} has joined your server {servername}"
    content: "A user with name {username} has joined your server on {datetime} at coordinates {coords}"
time:
  datetime-format: "yyyy-MM-dd HH:mm:ss"
notification:
  email:
    enabled: "true"
    passwordFromEnv: "true" # load password for authentication from env var by default, if false use field below
    server: "IMAP"
    serverAddress: "smtp.myserver.com"
    port: "465"
    username: "myusername"
    password: "mypassword"
# room for other systems configuration